logger: 
  level: debug
  devMode: true
  
http: 
  port: :8082

# redis: 
#   uri: "localhost:6379"

mongo:
  uri: "mongodb://user:password@mongodb:27017"
  db: profiles
  connectTimeout: 10s

nonce:
  exp: 900s

mongoCollections:
  profiles: profiles

authClientURL: "auth:8081"
s3Url: "s3:8083"